# ==============================================================================
# Copyright (c) 2026 HGA Authors. All rights reserved.
# Licensed under the MIT License. See LICENSE file in the project root for details.
# SPDX-License-Identifier: MIT
# Project: HGA (Hierarchical-Geometric Alignment)
# GitHub: https://github.com/Uncertainty-42/HGA
# ==============================================================================

"""
Hierarchical Region Restoration and Purification Engine.

This sub-package operates as the initial data-preparation stage within the HGA paradigm. 
Its primary function is to restore the raw hierarchical partition sequence (generated by 
NAMLab) into a target-level index map, and subsequently execute structural-affinity-based 
region purification to merge redundant, undersized fragments. 

Notably, while this module requires relative depth maps as input, the depth information 
serves exclusively as a guidance signal to evaluate inter-region geometric affinity 
during the purification process; the sole output of this module is the refined 
hierarchical region index map.

HGA Pipeline Context:
---------------------
The refined 2D index map produced by this module serves as the high-quality base material 
('namlab_raw') for the 'preprocess.py' module, where it undergoes scale-compensated 
Gaussian diffusion to synthesize a continuous attractor field, which is ultimately fed 
into the 'HGACriterion' ('losses.py') to guide online decision-competition alignment.

Minimal Integration Example (Inside a Custom DataLoader):
---------------------------------------------------------
    >>> from priors_optimization.namlab_refinement import run_namlab_refinement
    >>>
    >>> # Typical usage during the first epoch or data preparation phase:
    >>> # 'pt_data' is a dictionary loaded from the raw Hugging Face .pt files
    >>> refined_index_map = run_namlab_refinement(
    ...     pt_data=torch.load("path/to/raw_namlab.pt"),
    ...     img_rgb=np.asarray(imageio.imread("path/to/image.jpg")),
    ...     depth_raw=np.load("path/to/depth_map.npy"),
    ...     target_level=60,
    ...     purification_enabled=True,
    ...     area_threshold=4700.0
    ... )
    >>>
    >>> # The 'refined_index_map' (np.ndarray) can now be cached to disk or 
    >>> # passed directly to the Preprocessor module.
"""

from .core import run_namlab_refinement